// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type H128 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            uint64                 `protobuf:"varint,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            uint64                 `protobuf:"varint,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H128) Reset() {
	*x = H128{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H128) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H128) ProtoMessage() {}

func (x *H128) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H128.ProtoReflect.Descriptor instead.
func (*H128) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *H128) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

func (x *H128) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

type H160 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            *H128                  `protobuf:"bytes,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            uint32                 `protobuf:"varint,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H160) Reset() {
	*x = H160{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H160) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H160) ProtoMessage() {}

func (x *H160) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H160.ProtoReflect.Descriptor instead.
func (*H160) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *H160) GetHi() *H128 {
	if x != nil {
		return x.Hi
	}
	return nil
}

func (x *H160) GetLo() uint32 {
	if x != nil {
		return x.Lo
	}
	return 0
}

type H256 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            *H128                  `protobuf:"bytes,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            *H128                  `protobuf:"bytes,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H256) Reset() {
	*x = H256{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H256) ProtoMessage() {}

func (x *H256) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H256.ProtoReflect.Descriptor instead.
func (*H256) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *H256) GetHi() *H128 {
	if x != nil {
		return x.Hi
	}
	return nil
}

func (x *H256) GetLo() *H128 {
	if x != nil {
		return x.Lo
	}
	return nil
}

type H512 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            *H256                  `protobuf:"bytes,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            *H256                  `protobuf:"bytes,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H512) Reset() {
	*x = H512{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H512) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H512) ProtoMessage() {}

func (x *H512) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H512.ProtoReflect.Descriptor instead.
func (*H512) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *H512) GetHi() *H256 {
	if x != nil {
		return x.Hi
	}
	return nil
}

func (x *H512) GetLo() *H256 {
	if x != nil {
		return x.Lo
	}
	return nil
}

type H1024 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            *H512                  `protobuf:"bytes,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            *H512                  `protobuf:"bytes,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H1024) Reset() {
	*x = H1024{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H1024) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H1024) ProtoMessage() {}

func (x *H1024) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H1024.ProtoReflect.Descriptor instead.
func (*H1024) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *H1024) GetHi() *H512 {
	if x != nil {
		return x.Hi
	}
	return nil
}

func (x *H1024) GetLo() *H512 {
	if x != nil {
		return x.Lo
	}
	return nil
}

type H2048 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hi            *H1024                 `protobuf:"bytes,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo            *H1024                 `protobuf:"bytes,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H2048) Reset() {
	*x = H2048{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H2048) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H2048) ProtoMessage() {}

func (x *H2048) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H2048.ProtoReflect.Descriptor instead.
func (*H2048) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *H2048) GetHi() *H1024 {
	if x != nil {
		return x.Hi
	}
	return nil
}

func (x *H2048) GetLo() *H1024 {
	if x != nil {
		return x.Lo
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\"&\n" +
	"\x04H128\x12\x0e\n" +
	"\x02hi\x18\x01 \x01(\x04R\x02hi\x12\x0e\n" +
	"\x02lo\x18\x02 \x01(\x04R\x02lo\"3\n" +
	"\x04H160\x12\x1b\n" +
	"\x02hi\x18\x01 \x01(\v2\v.types.H128R\x02hi\x12\x0e\n" +
	"\x02lo\x18\x02 \x01(\rR\x02lo\"@\n" +
	"\x04H256\x12\x1b\n" +
	"\x02hi\x18\x01 \x01(\v2\v.types.H128R\x02hi\x12\x1b\n" +
	"\x02lo\x18\x02 \x01(\v2\v.types.H128R\x02lo\"@\n" +
	"\x04H512\x12\x1b\n" +
	"\x02hi\x18\x01 \x01(\v2\v.types.H256R\x02hi\x12\x1b\n" +
	"\x02lo\x18\x02 \x01(\v2\v.types.H256R\x02lo\"A\n" +
	"\x05H1024\x12\x1b\n" +
	"\x02hi\x18\x01 \x01(\v2\v.types.H512R\x02hi\x12\x1b\n" +
	"\x02lo\x18\x02 \x01(\v2\v.types.H512R\x02lo\"C\n" +
	"\x05H2048\x12\x1c\n" +
	"\x02hi\x18\x01 \x01(\v2\f.types.H1024R\x02hi\x12\x1c\n" +
	"\x02lo\x18\x02 \x01(\v2\f.types.H1024R\x02lob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_proto_goTypes = []any{
	(*H128)(nil),  // 0: types.H128
	(*H160)(nil),  // 1: types.H160
	(*H256)(nil),  // 2: types.H256
	(*H512)(nil),  // 3: types.H512
	(*H1024)(nil), // 4: types.H1024
	(*H2048)(nil), // 5: types.H2048
}
var file_types_proto_depIdxs = []int32{
	0, // 0: types.H160.hi:type_name -> types.H128
	0, // 1: types.H256.hi:type_name -> types.H128
	0, // 2: types.H256.lo:type_name -> types.H128
	2, // 3: types.H512.hi:type_name -> types.H256
	2, // 4: types.H512.lo:type_name -> types.H256
	3, // 5: types.H1024.hi:type_name -> types.H512
	3, // 6: types.H1024.lo:type_name -> types.H512
	4, // 7: types.H2048.hi:type_name -> types.H1024
	4, // 8: types.H2048.lo:type_name -> types.H1024
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
