// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package api

import (
	eth "github.com/chainbound/fiber-go/protobuf/eth"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxSequenceMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      []*eth.Transaction     `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSequenceMsg) Reset() {
	*x = TxSequenceMsg{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSequenceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSequenceMsg) ProtoMessage() {}

func (x *TxSequenceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSequenceMsg.ProtoReflect.Descriptor instead.
func (*TxSequenceMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *TxSequenceMsg) GetSequence() []*eth.Transaction {
	if x != nil {
		return x.Sequence
	}
	return nil
}

// / A message containing a sequence of enveloped, RLP-encoded transactions.
type TxSequenceMsgV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / list of enveloped, RLP-encoded transaction bytes.
	Sequence      [][]byte `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSequenceMsgV2) Reset() {
	*x = TxSequenceMsgV2{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSequenceMsgV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSequenceMsgV2) ProtoMessage() {}

func (x *TxSequenceMsgV2) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSequenceMsgV2.ProtoReflect.Descriptor instead.
func (*TxSequenceMsgV2) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *TxSequenceMsgV2) GetSequence() [][]byte {
	if x != nil {
		return x.Sequence
	}
	return nil
}

type RawTxSequenceMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawTxs        [][]byte               `protobuf:"bytes,1,rep,name=raw_txs,json=rawTxs,proto3" json:"raw_txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTxSequenceMsg) Reset() {
	*x = RawTxSequenceMsg{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTxSequenceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTxSequenceMsg) ProtoMessage() {}

func (x *RawTxSequenceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTxSequenceMsg.ProtoReflect.Descriptor instead.
func (*RawTxSequenceMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *RawTxSequenceMsg) GetRawTxs() [][]byte {
	if x != nil {
		return x.RawTxs
	}
	return nil
}

type TxSequenceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SequenceResponse []*TransactionResponse `protobuf:"bytes,1,rep,name=sequence_response,json=sequenceResponse,proto3" json:"sequence_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TxSequenceResponse) Reset() {
	*x = TxSequenceResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSequenceResponse) ProtoMessage() {}

func (x *TxSequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSequenceResponse.ProtoReflect.Descriptor instead.
func (*TxSequenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *TxSequenceResponse) GetSequenceResponse() []*TransactionResponse {
	if x != nil {
		return x.SequenceResponse
	}
	return nil
}

type TxFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       []byte                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxFilter) Reset() {
	*x = TxFilter{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxFilter) ProtoMessage() {}

func (x *TxFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxFilter.ProtoReflect.Descriptor instead.
func (*TxFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *TxFilter) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

type BlockFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producer      string                 `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockFilter) Reset() {
	*x = BlockFilter{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFilter) ProtoMessage() {}

func (x *BlockFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFilter.ProtoReflect.Descriptor instead.
func (*BlockFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *BlockFilter) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

type RawTxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawTx         []byte                 `protobuf:"bytes,1,opt,name=rawTx,proto3" json:"rawTx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTxMsg) Reset() {
	*x = RawTxMsg{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTxMsg) ProtoMessage() {}

func (x *RawTxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTxMsg.ProtoReflect.Descriptor instead.
func (*RawTxMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *RawTxMsg) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

type BlockSubmissionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SszBlock      []byte                 `protobuf:"bytes,1,opt,name=ssz_block,json=sszBlock,proto3" json:"ssz_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSubmissionMsg) Reset() {
	*x = BlockSubmissionMsg{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSubmissionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSubmissionMsg) ProtoMessage() {}

func (x *BlockSubmissionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSubmissionMsg.ProtoReflect.Descriptor instead.
func (*BlockSubmissionMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *BlockSubmissionMsg) GetSszBlock() []byte {
	if x != nil {
		return x.SszBlock
	}
	return nil
}

// / An enveloped, RLP-encoded transaction.
type TransactionMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The enveloped, RLP-encoded transaction bytes.
	RlpTransaction []byte `protobuf:"bytes,1,opt,name=rlp_transaction,json=rlpTransaction,proto3" json:"rlp_transaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionMsg) Reset() {
	*x = TransactionMsg{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMsg) ProtoMessage() {}

func (x *TransactionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMsg.ProtoReflect.Descriptor instead.
func (*TransactionMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionMsg) GetRlpTransaction() []byte {
	if x != nil {
		return x.RlpTransaction
	}
	return nil
}

type TransactionWithSenderMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The enveloped, RLP-encoded transaction bytes.
	RlpTransaction []byte `protobuf:"bytes,1,opt,name=rlp_transaction,json=rlpTransaction,proto3" json:"rlp_transaction,omitempty"`
	// / The address of the sender / signer.
	Sender        []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionWithSenderMsg) Reset() {
	*x = TransactionWithSenderMsg{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionWithSenderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionWithSenderMsg) ProtoMessage() {}

func (x *TransactionWithSenderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionWithSenderMsg.ProtoReflect.Descriptor instead.
func (*TransactionWithSenderMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionWithSenderMsg) GetRlpTransaction() []byte {
	if x != nil {
		return x.RlpTransaction
	}
	return nil
}

func (x *TransactionWithSenderMsg) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

// / An SSZ encoded execution payload.
type ExecutionPayloadMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fork data version.
	DataVersion uint32 `protobuf:"varint,1,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	// The SSZ encoded execution payload.
	SszPayload    []byte `protobuf:"bytes,2,opt,name=ssz_payload,json=sszPayload,proto3" json:"ssz_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadMsg) Reset() {
	*x = ExecutionPayloadMsg{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadMsg) ProtoMessage() {}

func (x *ExecutionPayloadMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadMsg.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionPayloadMsg) GetDataVersion() uint32 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

func (x *ExecutionPayloadMsg) GetSszPayload() []byte {
	if x != nil {
		return x.SszPayload
	}
	return nil
}

type BeaconBlockMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The beacon block version.
	DataVersion uint32 `protobuf:"varint,1,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	// The SSZ encoded beacon block.
	SszBlock      []byte `protobuf:"bytes,2,opt,name=ssz_block,json=sszBlock,proto3" json:"ssz_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconBlockMsg) Reset() {
	*x = BeaconBlockMsg{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlockMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlockMsg) ProtoMessage() {}

func (x *BeaconBlockMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlockMsg.ProtoReflect.Descriptor instead.
func (*BeaconBlockMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *BeaconBlockMsg) GetDataVersion() uint32 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

func (x *BeaconBlockMsg) GetSszBlock() []byte {
	if x != nil {
		return x.SszBlock
	}
	return nil
}

type BlockSubmissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The slot of the block.
	Slot uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// The re-calculated state root after reconstructing the block.
	StateRoot []byte `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// Timestamp in microseconds.
	Timestamp     uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSubmissionResponse) Reset() {
	*x = BlockSubmissionResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSubmissionResponse) ProtoMessage() {}

func (x *BlockSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSubmissionResponse.ProtoReflect.Descriptor instead.
func (*BlockSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *BlockSubmissionResponse) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BlockSubmissionResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockSubmissionResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TransactionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\teth.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\rTxSequenceMsg\x12,\n" +
	"\bsequence\x18\x01 \x03(\v2\x10.eth.TransactionR\bsequence\"-\n" +
	"\x0fTxSequenceMsgV2\x12\x1a\n" +
	"\bsequence\x18\x01 \x03(\fR\bsequence\"+\n" +
	"\x10RawTxSequenceMsg\x12\x17\n" +
	"\araw_txs\x18\x01 \x03(\fR\x06rawTxs\"[\n" +
	"\x12TxSequenceResponse\x12E\n" +
	"\x11sequence_response\x18\x01 \x03(\v2\x18.api.TransactionResponseR\x10sequenceResponse\"$\n" +
	"\bTxFilter\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\")\n" +
	"\vBlockFilter\x12\x1a\n" +
	"\bproducer\x18\x01 \x01(\tR\bproducer\" \n" +
	"\bRawTxMsg\x12\x14\n" +
	"\x05rawTx\x18\x01 \x01(\fR\x05rawTx\"1\n" +
	"\x12BlockSubmissionMsg\x12\x1b\n" +
	"\tssz_block\x18\x01 \x01(\fR\bsszBlock\"9\n" +
	"\x0eTransactionMsg\x12'\n" +
	"\x0frlp_transaction\x18\x01 \x01(\fR\x0erlpTransaction\"[\n" +
	"\x18TransactionWithSenderMsg\x12'\n" +
	"\x0frlp_transaction\x18\x01 \x01(\fR\x0erlpTransaction\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\"Y\n" +
	"\x13ExecutionPayloadMsg\x12!\n" +
	"\fdata_version\x18\x01 \x01(\rR\vdataVersion\x12\x1f\n" +
	"\vssz_payload\x18\x02 \x01(\fR\n" +
	"sszPayload\"P\n" +
	"\x0eBeaconBlockMsg\x12!\n" +
	"\fdata_version\x18\x01 \x01(\rR\vdataVersion\x12\x1b\n" +
	"\tssz_block\x18\x02 \x01(\fR\bsszBlock\"j\n" +
	"\x17BlockSubmissionResponse\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\fR\tstateRoot\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"G\n" +
	"\x13TransactionResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\x87\t\n" +
	"\x03API\x126\n" +
	"\x0fSubscribeNewTxs\x12\r.api.TxFilter\x1a\x10.eth.Transaction\"\x000\x01\x12E\n" +
	"\x11SubscribeNewTxsV2\x12\r.api.TxFilter\x1a\x1d.api.TransactionWithSenderMsg\"\x000\x01\x12P\n" +
	"\x13SubscribeNewBlobTxs\x12\x16.google.protobuf.Empty\x1a\x1d.api.TransactionWithSenderMsg\"\x000\x01\x12C\n" +
	"\x0fSendTransaction\x12\x10.eth.Transaction\x1a\x18.api.TransactionResponse\"\x00(\x010\x01\x12C\n" +
	"\x12SendRawTransaction\x12\r.api.RawTxMsg\x1a\x18.api.TransactionResponse\"\x00(\x010\x01\x12H\n" +
	"\x11SendTransactionV2\x12\x13.api.TransactionMsg\x1a\x18.api.TransactionResponse\"\x00(\x010\x01\x12L\n" +
	"\x17SendTransactionSequence\x12\x12.api.TxSequenceMsg\x1a\x17.api.TxSequenceResponse\"\x00(\x010\x01\x12P\n" +
	"\x19SendTransactionSequenceV2\x12\x14.api.TxSequenceMsgV2\x1a\x17.api.TxSequenceResponse\"\x00(\x010\x01\x12R\n" +
	"\x1aSendRawTransactionSequence\x12\x15.api.RawTxSequenceMsg\x1a\x17.api.TxSequenceResponse\"\x00(\x010\x01\x12O\n" +
	"\x1aSubscribeExecutionPayloads\x12\x16.google.protobuf.Empty\x1a\x15.eth.ExecutionPayload\"\x000\x01\x12T\n" +
	"\x1cSubscribeExecutionPayloadsV2\x12\x16.google.protobuf.Empty\x1a\x18.api.ExecutionPayloadMsg\"\x000\x01\x12T\n" +
	"\x19SubscribeExecutionHeaders\x12\x16.google.protobuf.Empty\x1a\x1b.eth.ExecutionPayloadHeader\"\x000\x01\x12L\n" +
	"\x15SubscribeBeaconBlocks\x12\x16.google.protobuf.Empty\x1a\x17.eth.CompactBeaconBlock\"\x000\x01\x12J\n" +
	"\x17SubscribeBeaconBlocksV2\x12\x16.google.protobuf.Empty\x1a\x13.api.BeaconBlockMsg\"\x000\x01\x12P\n" +
	"\x11SubmitBlockStream\x12\x17.api.BlockSubmissionMsg\x1a\x1c.api.BlockSubmissionResponse\"\x00(\x010\x01b\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_goTypes = []any{
	(*TxSequenceMsg)(nil),              // 0: api.TxSequenceMsg
	(*TxSequenceMsgV2)(nil),            // 1: api.TxSequenceMsgV2
	(*RawTxSequenceMsg)(nil),           // 2: api.RawTxSequenceMsg
	(*TxSequenceResponse)(nil),         // 3: api.TxSequenceResponse
	(*TxFilter)(nil),                   // 4: api.TxFilter
	(*BlockFilter)(nil),                // 5: api.BlockFilter
	(*RawTxMsg)(nil),                   // 6: api.RawTxMsg
	(*BlockSubmissionMsg)(nil),         // 7: api.BlockSubmissionMsg
	(*TransactionMsg)(nil),             // 8: api.TransactionMsg
	(*TransactionWithSenderMsg)(nil),   // 9: api.TransactionWithSenderMsg
	(*ExecutionPayloadMsg)(nil),        // 10: api.ExecutionPayloadMsg
	(*BeaconBlockMsg)(nil),             // 11: api.BeaconBlockMsg
	(*BlockSubmissionResponse)(nil),    // 12: api.BlockSubmissionResponse
	(*TransactionResponse)(nil),        // 13: api.TransactionResponse
	(*eth.Transaction)(nil),            // 14: eth.Transaction
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
	(*eth.ExecutionPayload)(nil),       // 16: eth.ExecutionPayload
	(*eth.ExecutionPayloadHeader)(nil), // 17: eth.ExecutionPayloadHeader
	(*eth.CompactBeaconBlock)(nil),     // 18: eth.CompactBeaconBlock
}
var file_api_proto_depIdxs = []int32{
	14, // 0: api.TxSequenceMsg.sequence:type_name -> eth.Transaction
	13, // 1: api.TxSequenceResponse.sequence_response:type_name -> api.TransactionResponse
	4,  // 2: api.API.SubscribeNewTxs:input_type -> api.TxFilter
	4,  // 3: api.API.SubscribeNewTxsV2:input_type -> api.TxFilter
	15, // 4: api.API.SubscribeNewBlobTxs:input_type -> google.protobuf.Empty
	14, // 5: api.API.SendTransaction:input_type -> eth.Transaction
	6,  // 6: api.API.SendRawTransaction:input_type -> api.RawTxMsg
	8,  // 7: api.API.SendTransactionV2:input_type -> api.TransactionMsg
	0,  // 8: api.API.SendTransactionSequence:input_type -> api.TxSequenceMsg
	1,  // 9: api.API.SendTransactionSequenceV2:input_type -> api.TxSequenceMsgV2
	2,  // 10: api.API.SendRawTransactionSequence:input_type -> api.RawTxSequenceMsg
	15, // 11: api.API.SubscribeExecutionPayloads:input_type -> google.protobuf.Empty
	15, // 12: api.API.SubscribeExecutionPayloadsV2:input_type -> google.protobuf.Empty
	15, // 13: api.API.SubscribeExecutionHeaders:input_type -> google.protobuf.Empty
	15, // 14: api.API.SubscribeBeaconBlocks:input_type -> google.protobuf.Empty
	15, // 15: api.API.SubscribeBeaconBlocksV2:input_type -> google.protobuf.Empty
	7,  // 16: api.API.SubmitBlockStream:input_type -> api.BlockSubmissionMsg
	14, // 17: api.API.SubscribeNewTxs:output_type -> eth.Transaction
	9,  // 18: api.API.SubscribeNewTxsV2:output_type -> api.TransactionWithSenderMsg
	9,  // 19: api.API.SubscribeNewBlobTxs:output_type -> api.TransactionWithSenderMsg
	13, // 20: api.API.SendTransaction:output_type -> api.TransactionResponse
	13, // 21: api.API.SendRawTransaction:output_type -> api.TransactionResponse
	13, // 22: api.API.SendTransactionV2:output_type -> api.TransactionResponse
	3,  // 23: api.API.SendTransactionSequence:output_type -> api.TxSequenceResponse
	3,  // 24: api.API.SendTransactionSequenceV2:output_type -> api.TxSequenceResponse
	3,  // 25: api.API.SendRawTransactionSequence:output_type -> api.TxSequenceResponse
	16, // 26: api.API.SubscribeExecutionPayloads:output_type -> eth.ExecutionPayload
	10, // 27: api.API.SubscribeExecutionPayloadsV2:output_type -> api.ExecutionPayloadMsg
	17, // 28: api.API.SubscribeExecutionHeaders:output_type -> eth.ExecutionPayloadHeader
	18, // 29: api.API.SubscribeBeaconBlocks:output_type -> eth.CompactBeaconBlock
	11, // 30: api.API.SubscribeBeaconBlocksV2:output_type -> api.BeaconBlockMsg
	12, // 31: api.API.SubmitBlockStream:output_type -> api.BlockSubmissionResponse
	17, // [17:32] is the sub-list for method output_type
	2,  // [2:17] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
