// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: api.proto

package api

import (
	context "context"
	eth "github.com/chainbound/fiber-go/protobuf/eth"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	// Opens a new transaction stream with the given filter.
	SubscribeNewTxs(ctx context.Context, in *TxFilter, opts ...grpc.CallOption) (API_SubscribeNewTxsClient, error)
	// Sends a signed transaction to the network.
	SendTransaction(ctx context.Context, opts ...grpc.CallOption) (API_SendTransactionClient, error)
	// Sends a signed, RLP encoded transaction to the network
	SendRawTransaction(ctx context.Context, opts ...grpc.CallOption) (API_SendRawTransactionClient, error)
	// Sends a sequence of signed transactions to the network.
	SendTransactionSequence(ctx context.Context, opts ...grpc.CallOption) (API_SendTransactionSequenceClient, error)
	// Sends a sequence of signed, RLP encoded transactions to the network.
	SendRawTransactionSequence(ctx context.Context, opts ...grpc.CallOption) (API_SendRawTransactionSequenceClient, error)
	// Opens a stream of new execution payloads.
	SubscribeExecutionPayloads(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_SubscribeExecutionPayloadsClient, error)
	// Opens a stream of new execution payload headers.
	SubscribeExecutionHeaders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_SubscribeExecutionHeadersClient, error)
	// Opens a stream of new beacon blocks. The beacon blocks are "compacted", meaning that the
	// execution payload is not included.
	SubscribeBeaconBlocks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_SubscribeBeaconBlocksClient, error)
	// Opens a bi-directional stream for new block submissions. The client stream is used to send
	// SSZ-encoded beacon blocks, and the server stream is used to send back the state_root, slot and
	// a local timestamp as a confirmation that the block was seen and handled.
	SubmitBlockStream(ctx context.Context, opts ...grpc.CallOption) (API_SubmitBlockStreamClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) SubscribeNewTxs(ctx context.Context, in *TxFilter, opts ...grpc.CallOption) (API_SubscribeNewTxsClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[0], "/api.API/SubscribeNewTxs", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubscribeNewTxsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SubscribeNewTxsClient interface {
	Recv() (*eth.Transaction, error)
	grpc.ClientStream
}

type aPISubscribeNewTxsClient struct {
	grpc.ClientStream
}

func (x *aPISubscribeNewTxsClient) Recv() (*eth.Transaction, error) {
	m := new(eth.Transaction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendTransaction(ctx context.Context, opts ...grpc.CallOption) (API_SendTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[1], "/api.API/SendTransaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendTransactionClient{stream}
	return x, nil
}

type API_SendTransactionClient interface {
	Send(*eth.Transaction) error
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type aPISendTransactionClient struct {
	grpc.ClientStream
}

func (x *aPISendTransactionClient) Send(m *eth.Transaction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendTransactionClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendRawTransaction(ctx context.Context, opts ...grpc.CallOption) (API_SendRawTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[2], "/api.API/SendRawTransaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendRawTransactionClient{stream}
	return x, nil
}

type API_SendRawTransactionClient interface {
	Send(*RawTxMsg) error
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type aPISendRawTransactionClient struct {
	grpc.ClientStream
}

func (x *aPISendRawTransactionClient) Send(m *RawTxMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendRawTransactionClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendTransactionSequence(ctx context.Context, opts ...grpc.CallOption) (API_SendTransactionSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[3], "/api.API/SendTransactionSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendTransactionSequenceClient{stream}
	return x, nil
}

type API_SendTransactionSequenceClient interface {
	Send(*TxSequenceMsg) error
	Recv() (*TxSequenceResponse, error)
	grpc.ClientStream
}

type aPISendTransactionSequenceClient struct {
	grpc.ClientStream
}

func (x *aPISendTransactionSequenceClient) Send(m *TxSequenceMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendTransactionSequenceClient) Recv() (*TxSequenceResponse, error) {
	m := new(TxSequenceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SendRawTransactionSequence(ctx context.Context, opts ...grpc.CallOption) (API_SendRawTransactionSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[4], "/api.API/SendRawTransactionSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISendRawTransactionSequenceClient{stream}
	return x, nil
}

type API_SendRawTransactionSequenceClient interface {
	Send(*RawTxSequenceMsg) error
	Recv() (*TxSequenceResponse, error)
	grpc.ClientStream
}

type aPISendRawTransactionSequenceClient struct {
	grpc.ClientStream
}

func (x *aPISendRawTransactionSequenceClient) Send(m *RawTxSequenceMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISendRawTransactionSequenceClient) Recv() (*TxSequenceResponse, error) {
	m := new(TxSequenceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SubscribeExecutionPayloads(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_SubscribeExecutionPayloadsClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[5], "/api.API/SubscribeExecutionPayloads", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubscribeExecutionPayloadsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SubscribeExecutionPayloadsClient interface {
	Recv() (*eth.ExecutionPayload, error)
	grpc.ClientStream
}

type aPISubscribeExecutionPayloadsClient struct {
	grpc.ClientStream
}

func (x *aPISubscribeExecutionPayloadsClient) Recv() (*eth.ExecutionPayload, error) {
	m := new(eth.ExecutionPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SubscribeExecutionHeaders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_SubscribeExecutionHeadersClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[6], "/api.API/SubscribeExecutionHeaders", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubscribeExecutionHeadersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SubscribeExecutionHeadersClient interface {
	Recv() (*eth.ExecutionPayloadHeader, error)
	grpc.ClientStream
}

type aPISubscribeExecutionHeadersClient struct {
	grpc.ClientStream
}

func (x *aPISubscribeExecutionHeadersClient) Recv() (*eth.ExecutionPayloadHeader, error) {
	m := new(eth.ExecutionPayloadHeader)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SubscribeBeaconBlocks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (API_SubscribeBeaconBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[7], "/api.API/SubscribeBeaconBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubscribeBeaconBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SubscribeBeaconBlocksClient interface {
	Recv() (*eth.CompactBeaconBlock, error)
	grpc.ClientStream
}

type aPISubscribeBeaconBlocksClient struct {
	grpc.ClientStream
}

func (x *aPISubscribeBeaconBlocksClient) Recv() (*eth.CompactBeaconBlock, error) {
	m := new(eth.CompactBeaconBlock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) SubmitBlockStream(ctx context.Context, opts ...grpc.CallOption) (API_SubmitBlockStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[8], "/api.API/SubmitBlockStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubmitBlockStreamClient{stream}
	return x, nil
}

type API_SubmitBlockStreamClient interface {
	Send(*BlockSubmissionMsg) error
	Recv() (*BlockSubmissionResponse, error)
	grpc.ClientStream
}

type aPISubmitBlockStreamClient struct {
	grpc.ClientStream
}

func (x *aPISubmitBlockStreamClient) Send(m *BlockSubmissionMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPISubmitBlockStreamClient) Recv() (*BlockSubmissionResponse, error) {
	m := new(BlockSubmissionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility
type APIServer interface {
	// Opens a new transaction stream with the given filter.
	SubscribeNewTxs(*TxFilter, API_SubscribeNewTxsServer) error
	// Sends a signed transaction to the network.
	SendTransaction(API_SendTransactionServer) error
	// Sends a signed, RLP encoded transaction to the network
	SendRawTransaction(API_SendRawTransactionServer) error
	// Sends a sequence of signed transactions to the network.
	SendTransactionSequence(API_SendTransactionSequenceServer) error
	// Sends a sequence of signed, RLP encoded transactions to the network.
	SendRawTransactionSequence(API_SendRawTransactionSequenceServer) error
	// Opens a stream of new execution payloads.
	SubscribeExecutionPayloads(*emptypb.Empty, API_SubscribeExecutionPayloadsServer) error
	// Opens a stream of new execution payload headers.
	SubscribeExecutionHeaders(*emptypb.Empty, API_SubscribeExecutionHeadersServer) error
	// Opens a stream of new beacon blocks. The beacon blocks are "compacted", meaning that the
	// execution payload is not included.
	SubscribeBeaconBlocks(*emptypb.Empty, API_SubscribeBeaconBlocksServer) error
	// Opens a bi-directional stream for new block submissions. The client stream is used to send
	// SSZ-encoded beacon blocks, and the server stream is used to send back the state_root, slot and
	// a local timestamp as a confirmation that the block was seen and handled.
	SubmitBlockStream(API_SubmitBlockStreamServer) error
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (UnimplementedAPIServer) SubscribeNewTxs(*TxFilter, API_SubscribeNewTxsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeNewTxs not implemented")
}
func (UnimplementedAPIServer) SendTransaction(API_SendTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (UnimplementedAPIServer) SendRawTransaction(API_SendRawTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method SendRawTransaction not implemented")
}
func (UnimplementedAPIServer) SendTransactionSequence(API_SendTransactionSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method SendTransactionSequence not implemented")
}
func (UnimplementedAPIServer) SendRawTransactionSequence(API_SendRawTransactionSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method SendRawTransactionSequence not implemented")
}
func (UnimplementedAPIServer) SubscribeExecutionPayloads(*emptypb.Empty, API_SubscribeExecutionPayloadsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeExecutionPayloads not implemented")
}
func (UnimplementedAPIServer) SubscribeExecutionHeaders(*emptypb.Empty, API_SubscribeExecutionHeadersServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeExecutionHeaders not implemented")
}
func (UnimplementedAPIServer) SubscribeBeaconBlocks(*emptypb.Empty, API_SubscribeBeaconBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeBeaconBlocks not implemented")
}
func (UnimplementedAPIServer) SubmitBlockStream(API_SubmitBlockStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubmitBlockStream not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_SubscribeNewTxs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TxFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SubscribeNewTxs(m, &aPISubscribeNewTxsServer{stream})
}

type API_SubscribeNewTxsServer interface {
	Send(*eth.Transaction) error
	grpc.ServerStream
}

type aPISubscribeNewTxsServer struct {
	grpc.ServerStream
}

func (x *aPISubscribeNewTxsServer) Send(m *eth.Transaction) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SendTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendTransaction(&aPISendTransactionServer{stream})
}

type API_SendTransactionServer interface {
	Send(*TransactionResponse) error
	Recv() (*eth.Transaction, error)
	grpc.ServerStream
}

type aPISendTransactionServer struct {
	grpc.ServerStream
}

func (x *aPISendTransactionServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendTransactionServer) Recv() (*eth.Transaction, error) {
	m := new(eth.Transaction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendRawTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendRawTransaction(&aPISendRawTransactionServer{stream})
}

type API_SendRawTransactionServer interface {
	Send(*TransactionResponse) error
	Recv() (*RawTxMsg, error)
	grpc.ServerStream
}

type aPISendRawTransactionServer struct {
	grpc.ServerStream
}

func (x *aPISendRawTransactionServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendRawTransactionServer) Recv() (*RawTxMsg, error) {
	m := new(RawTxMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendTransactionSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendTransactionSequence(&aPISendTransactionSequenceServer{stream})
}

type API_SendTransactionSequenceServer interface {
	Send(*TxSequenceResponse) error
	Recv() (*TxSequenceMsg, error)
	grpc.ServerStream
}

type aPISendTransactionSequenceServer struct {
	grpc.ServerStream
}

func (x *aPISendTransactionSequenceServer) Send(m *TxSequenceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendTransactionSequenceServer) Recv() (*TxSequenceMsg, error) {
	m := new(TxSequenceMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SendRawTransactionSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SendRawTransactionSequence(&aPISendRawTransactionSequenceServer{stream})
}

type API_SendRawTransactionSequenceServer interface {
	Send(*TxSequenceResponse) error
	Recv() (*RawTxSequenceMsg, error)
	grpc.ServerStream
}

type aPISendRawTransactionSequenceServer struct {
	grpc.ServerStream
}

func (x *aPISendRawTransactionSequenceServer) Send(m *TxSequenceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISendRawTransactionSequenceServer) Recv() (*RawTxSequenceMsg, error) {
	m := new(RawTxSequenceMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_SubscribeExecutionPayloads_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SubscribeExecutionPayloads(m, &aPISubscribeExecutionPayloadsServer{stream})
}

type API_SubscribeExecutionPayloadsServer interface {
	Send(*eth.ExecutionPayload) error
	grpc.ServerStream
}

type aPISubscribeExecutionPayloadsServer struct {
	grpc.ServerStream
}

func (x *aPISubscribeExecutionPayloadsServer) Send(m *eth.ExecutionPayload) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SubscribeExecutionHeaders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SubscribeExecutionHeaders(m, &aPISubscribeExecutionHeadersServer{stream})
}

type API_SubscribeExecutionHeadersServer interface {
	Send(*eth.ExecutionPayloadHeader) error
	grpc.ServerStream
}

type aPISubscribeExecutionHeadersServer struct {
	grpc.ServerStream
}

func (x *aPISubscribeExecutionHeadersServer) Send(m *eth.ExecutionPayloadHeader) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SubscribeBeaconBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SubscribeBeaconBlocks(m, &aPISubscribeBeaconBlocksServer{stream})
}

type API_SubscribeBeaconBlocksServer interface {
	Send(*eth.CompactBeaconBlock) error
	grpc.ServerStream
}

type aPISubscribeBeaconBlocksServer struct {
	grpc.ServerStream
}

func (x *aPISubscribeBeaconBlocksServer) Send(m *eth.CompactBeaconBlock) error {
	return x.ServerStream.SendMsg(m)
}

func _API_SubmitBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).SubmitBlockStream(&aPISubmitBlockStreamServer{stream})
}

type API_SubmitBlockStreamServer interface {
	Send(*BlockSubmissionResponse) error
	Recv() (*BlockSubmissionMsg, error)
	grpc.ServerStream
}

type aPISubmitBlockStreamServer struct {
	grpc.ServerStream
}

func (x *aPISubmitBlockStreamServer) Send(m *BlockSubmissionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPISubmitBlockStreamServer) Recv() (*BlockSubmissionMsg, error) {
	m := new(BlockSubmissionMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.API",
	HandlerType: (*APIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeNewTxs",
			Handler:       _API_SubscribeNewTxs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendTransaction",
			Handler:       _API_SendTransaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendRawTransaction",
			Handler:       _API_SendRawTransaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendTransactionSequence",
			Handler:       _API_SendTransactionSequence_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendRawTransactionSequence",
			Handler:       _API_SendRawTransactionSequence_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeExecutionPayloads",
			Handler:       _API_SubscribeExecutionPayloads_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeExecutionHeaders",
			Handler:       _API_SubscribeExecutionHeaders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBeaconBlocks",
			Handler:       _API_SubscribeBeaconBlocks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubmitBlockStream",
			Handler:       _API_SubmitBlockStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
