// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: eth.proto

package eth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Typed transaction
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []byte                 `protobuf:"bytes,1,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Gas           uint64                 `protobuf:"varint,2,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      uint64                 `protobuf:"varint,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Hash          []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Input         []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Nonce         uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	From          []byte                 `protobuf:"bytes,8,opt,name=from,proto3,oneof" json:"from,omitempty"`
	Type          uint32                 `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	MaxFee        uint64                 `protobuf:"varint,10,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`                // = maxFeePerGas = GasFeeCap
	PriorityFee   uint64                 `protobuf:"varint,11,opt,name=priority_fee,json=priorityFee,proto3" json:"priority_fee,omitempty"` // = maxPriorityFeePerGas = GasTipCap
	V             uint64                 `protobuf:"varint,12,opt,name=v,proto3" json:"v,omitempty"`
	R             []byte                 `protobuf:"bytes,13,opt,name=r,proto3" json:"r,omitempty"`
	S             []byte                 `protobuf:"bytes,14,opt,name=s,proto3" json:"s,omitempty"`
	ChainId       uint32                 `protobuf:"varint,15,opt,name=chainId,proto3" json:"chainId,omitempty"`
	AccessList    []*AccessTuple         `protobuf:"bytes,16,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_eth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *Transaction) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *Transaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Transaction) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Transaction) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transaction) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Transaction) GetMaxFee() uint64 {
	if x != nil {
		return x.MaxFee
	}
	return 0
}

func (x *Transaction) GetPriorityFee() uint64 {
	if x != nil {
		return x.PriorityFee
	}
	return 0
}

func (x *Transaction) GetV() uint64 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *Transaction) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Transaction) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Transaction) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Transaction) GetAccessList() []*AccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

type AccessTuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StorageKeys   [][]byte               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTuple) Reset() {
	*x = AccessTuple{}
	mi := &file_eth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTuple) ProtoMessage() {}

func (x *AccessTuple) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTuple.ProtoReflect.Descriptor instead.
func (*AccessTuple) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTuple) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccessTuple) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

// An execution payload
// Last update: Capella
// We don't include the withdrawals because we're not interested in them
// and they add some overhead.
type ExecutionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The execution payload header
	Header        *ExecutionPayloadHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions  []*Transaction          `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayload) Reset() {
	*x = ExecutionPayload{}
	mi := &file_eth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayload) ProtoMessage() {}

func (x *ExecutionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayload.ProtoReflect.Descriptor instead.
func (*ExecutionPayload) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionPayload) GetHeader() *ExecutionPayloadHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ExecutionPayload) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// The execution payload header: https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#executionpayloadheader
// Last update: Capella
type ExecutionPayloadHeader struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ParentHash   []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot    []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom    []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao   []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber  uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit     uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed      uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp    uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData    []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	// Big endian encoded U256
	BaseFeePerGas    []byte `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash        []byte `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TransactionsRoot []byte `protobuf:"bytes,14,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	// Only: Capella
	WithdrawalsRoot []byte `protobuf:"bytes,15,opt,name=withdrawals_root,json=withdrawalsRoot,proto3,oneof" json:"withdrawals_root,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionPayloadHeader) Reset() {
	*x = ExecutionPayloadHeader{}
	mi := &file_eth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadHeader) ProtoMessage() {}

func (x *ExecutionPayloadHeader) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadHeader.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadHeader) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionPayloadHeader) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadHeader) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetTransactionsRoot() []byte {
	if x != nil {
		return x.TransactionsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeader) GetWithdrawalsRoot() []byte {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

// The beacon block: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#beaconblock
// Last update: Phase0
type BeaconBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ProposerIndex uint64                 `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	ParentRoot    []byte                 `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Body          *BeaconBlockBody       `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconBlock) Reset() {
	*x = BeaconBlock{}
	mi := &file_eth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlock) ProtoMessage() {}

func (x *BeaconBlock) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlock.ProtoReflect.Descriptor instead.
func (*BeaconBlock) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{4}
}

func (x *BeaconBlock) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BeaconBlock) GetProposerIndex() uint64 {
	if x != nil {
		return x.ProposerIndex
	}
	return 0
}

func (x *BeaconBlock) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *BeaconBlock) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BeaconBlock) GetBody() *BeaconBlockBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// Type that follows [`BeaconBlock`] but without the execution payload, relying
// on [`CompactBeaconBlockBody`] instead.
type CompactBeaconBlock struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Slot          uint64                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ProposerIndex uint64                  `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	ParentRoot    []byte                  `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot     []byte                  `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Body          *CompactBeaconBlockBody `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactBeaconBlock) Reset() {
	*x = CompactBeaconBlock{}
	mi := &file_eth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactBeaconBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactBeaconBlock) ProtoMessage() {}

func (x *CompactBeaconBlock) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactBeaconBlock.ProtoReflect.Descriptor instead.
func (*CompactBeaconBlock) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{5}
}

func (x *CompactBeaconBlock) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CompactBeaconBlock) GetProposerIndex() uint64 {
	if x != nil {
		return x.ProposerIndex
	}
	return 0
}

func (x *CompactBeaconBlock) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *CompactBeaconBlock) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *CompactBeaconBlock) GetBody() *CompactBeaconBlockBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#signedbeaconblock
type SignedBeaconBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *BeaconBlock           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBeaconBlock) Reset() {
	*x = SignedBeaconBlock{}
	mi := &file_eth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBeaconBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBeaconBlock) ProtoMessage() {}

func (x *SignedBeaconBlock) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBeaconBlock.ProtoReflect.Descriptor instead.
func (*SignedBeaconBlock) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{6}
}

func (x *SignedBeaconBlock) GetMessage() *BeaconBlock {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedBeaconBlock) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// The beacon block body: https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#beaconblockbody
// Last update: Capella
type BeaconBlockBody struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RandaoReveal      []byte                 `protobuf:"bytes,1,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty"`
	Eth1Data          *Eth1Data              `protobuf:"bytes,2,opt,name=eth1_data,json=eth1Data,proto3" json:"eth1_data,omitempty"`
	Graffiti          []byte                 `protobuf:"bytes,3,opt,name=graffiti,proto3" json:"graffiti,omitempty"`
	ProposerSlashings []*ProposerSlashing    `protobuf:"bytes,4,rep,name=proposer_slashings,json=proposerSlashings,proto3" json:"proposer_slashings,omitempty"`
	AttesterSlashings []*AttesterSlashing    `protobuf:"bytes,5,rep,name=attester_slashings,json=attesterSlashings,proto3" json:"attester_slashings,omitempty"`
	Attestations      []*Attestation         `protobuf:"bytes,6,rep,name=attestations,proto3" json:"attestations,omitempty"`
	Deposits          []*Deposit             `protobuf:"bytes,7,rep,name=deposits,proto3" json:"deposits,omitempty"`
	VoluntaryExits    []*SignedVoluntaryExit `protobuf:"bytes,8,rep,name=voluntary_exits,json=voluntaryExits,proto3" json:"voluntary_exits,omitempty"`
	SyncAggregate     *SyncAggregate         `protobuf:"bytes,9,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	ExecutionPayload  *ExecutionPayload      `protobuf:"bytes,10,opt,name=execution_payload,json=executionPayload,proto3" json:"execution_payload,omitempty"`
	// Only: Capella
	BlsToExecutionChanges []*SignedBLSToExecutionChange `protobuf:"bytes,11,rep,name=bls_to_execution_changes,json=blsToExecutionChanges,proto3" json:"bls_to_execution_changes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BeaconBlockBody) Reset() {
	*x = BeaconBlockBody{}
	mi := &file_eth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlockBody) ProtoMessage() {}

func (x *BeaconBlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlockBody.ProtoReflect.Descriptor instead.
func (*BeaconBlockBody) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{7}
}

func (x *BeaconBlockBody) GetRandaoReveal() []byte {
	if x != nil {
		return x.RandaoReveal
	}
	return nil
}

func (x *BeaconBlockBody) GetEth1Data() *Eth1Data {
	if x != nil {
		return x.Eth1Data
	}
	return nil
}

func (x *BeaconBlockBody) GetGraffiti() []byte {
	if x != nil {
		return x.Graffiti
	}
	return nil
}

func (x *BeaconBlockBody) GetProposerSlashings() []*ProposerSlashing {
	if x != nil {
		return x.ProposerSlashings
	}
	return nil
}

func (x *BeaconBlockBody) GetAttesterSlashings() []*AttesterSlashing {
	if x != nil {
		return x.AttesterSlashings
	}
	return nil
}

func (x *BeaconBlockBody) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *BeaconBlockBody) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *BeaconBlockBody) GetVoluntaryExits() []*SignedVoluntaryExit {
	if x != nil {
		return x.VoluntaryExits
	}
	return nil
}

func (x *BeaconBlockBody) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *BeaconBlockBody) GetExecutionPayload() *ExecutionPayload {
	if x != nil {
		return x.ExecutionPayload
	}
	return nil
}

func (x *BeaconBlockBody) GetBlsToExecutionChanges() []*SignedBLSToExecutionChange {
	if x != nil {
		return x.BlsToExecutionChanges
	}
	return nil
}

// Custom type that follows [`BeaconBlockBody`] but without the execution payload.
type CompactBeaconBlockBody struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RandaoReveal      []byte                 `protobuf:"bytes,1,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty"`
	Eth1Data          *Eth1Data              `protobuf:"bytes,2,opt,name=eth1_data,json=eth1Data,proto3" json:"eth1_data,omitempty"`
	Graffiti          []byte                 `protobuf:"bytes,3,opt,name=graffiti,proto3" json:"graffiti,omitempty"`
	ProposerSlashings []*ProposerSlashing    `protobuf:"bytes,4,rep,name=proposer_slashings,json=proposerSlashings,proto3" json:"proposer_slashings,omitempty"`
	AttesterSlashings []*AttesterSlashing    `protobuf:"bytes,5,rep,name=attester_slashings,json=attesterSlashings,proto3" json:"attester_slashings,omitempty"`
	Attestations      []*Attestation         `protobuf:"bytes,6,rep,name=attestations,proto3" json:"attestations,omitempty"`
	Deposits          []*Deposit             `protobuf:"bytes,7,rep,name=deposits,proto3" json:"deposits,omitempty"`
	VoluntaryExits    []*SignedVoluntaryExit `protobuf:"bytes,8,rep,name=voluntary_exits,json=voluntaryExits,proto3" json:"voluntary_exits,omitempty"`
	SyncAggregate     *SyncAggregate         `protobuf:"bytes,9,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	// Only: Capella
	BlsToExecutionChanges []*SignedBLSToExecutionChange `protobuf:"bytes,10,rep,name=bls_to_execution_changes,json=blsToExecutionChanges,proto3" json:"bls_to_execution_changes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CompactBeaconBlockBody) Reset() {
	*x = CompactBeaconBlockBody{}
	mi := &file_eth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactBeaconBlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactBeaconBlockBody) ProtoMessage() {}

func (x *CompactBeaconBlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactBeaconBlockBody.ProtoReflect.Descriptor instead.
func (*CompactBeaconBlockBody) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{8}
}

func (x *CompactBeaconBlockBody) GetRandaoReveal() []byte {
	if x != nil {
		return x.RandaoReveal
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetEth1Data() *Eth1Data {
	if x != nil {
		return x.Eth1Data
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetGraffiti() []byte {
	if x != nil {
		return x.Graffiti
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetProposerSlashings() []*ProposerSlashing {
	if x != nil {
		return x.ProposerSlashings
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetAttesterSlashings() []*AttesterSlashing {
	if x != nil {
		return x.AttesterSlashings
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetVoluntaryExits() []*SignedVoluntaryExit {
	if x != nil {
		return x.VoluntaryExits
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *CompactBeaconBlockBody) GetBlsToExecutionChanges() []*SignedBLSToExecutionChange {
	if x != nil {
		return x.BlsToExecutionChanges
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#signedbeaconblockheader
type SignedBeaconBlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *BeaconBlockHeader     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBeaconBlockHeader) Reset() {
	*x = SignedBeaconBlockHeader{}
	mi := &file_eth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBeaconBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBeaconBlockHeader) ProtoMessage() {}

func (x *SignedBeaconBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBeaconBlockHeader.ProtoReflect.Descriptor instead.
func (*SignedBeaconBlockHeader) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{9}
}

func (x *SignedBeaconBlockHeader) GetMessage() *BeaconBlockHeader {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedBeaconBlockHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#beaconblockheader
type BeaconBlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ProposerIndex uint64                 `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	ParentRoot    []byte                 `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BodyRoot      []byte                 `protobuf:"bytes,5,opt,name=body_root,json=bodyRoot,proto3" json:"body_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconBlockHeader) Reset() {
	*x = BeaconBlockHeader{}
	mi := &file_eth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlockHeader) ProtoMessage() {}

func (x *BeaconBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlockHeader.ProtoReflect.Descriptor instead.
func (*BeaconBlockHeader) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{10}
}

func (x *BeaconBlockHeader) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BeaconBlockHeader) GetProposerIndex() uint64 {
	if x != nil {
		return x.ProposerIndex
	}
	return 0
}

func (x *BeaconBlockHeader) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *BeaconBlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BeaconBlockHeader) GetBodyRoot() []byte {
	if x != nil {
		return x.BodyRoot
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#eth1data
type Eth1Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepositRoot   []byte                 `protobuf:"bytes,1,opt,name=deposit_root,json=depositRoot,proto3" json:"deposit_root,omitempty"`
	DepositCount  uint64                 `protobuf:"varint,2,opt,name=deposit_count,json=depositCount,proto3" json:"deposit_count,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eth1Data) Reset() {
	*x = Eth1Data{}
	mi := &file_eth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eth1Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eth1Data) ProtoMessage() {}

func (x *Eth1Data) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eth1Data.ProtoReflect.Descriptor instead.
func (*Eth1Data) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{11}
}

func (x *Eth1Data) GetDepositRoot() []byte {
	if x != nil {
		return x.DepositRoot
	}
	return nil
}

func (x *Eth1Data) GetDepositCount() uint64 {
	if x != nil {
		return x.DepositCount
	}
	return 0
}

func (x *Eth1Data) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#signedvoluntaryexit
type SignedVoluntaryExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *VoluntaryExit         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedVoluntaryExit) Reset() {
	*x = SignedVoluntaryExit{}
	mi := &file_eth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedVoluntaryExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedVoluntaryExit) ProtoMessage() {}

func (x *SignedVoluntaryExit) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedVoluntaryExit.ProtoReflect.Descriptor instead.
func (*SignedVoluntaryExit) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{12}
}

func (x *SignedVoluntaryExit) GetMessage() *VoluntaryExit {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedVoluntaryExit) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#voluntaryexit
type VoluntaryExit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Epoch          uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ValidatorIndex uint64                 `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoluntaryExit) Reset() {
	*x = VoluntaryExit{}
	mi := &file_eth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoluntaryExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoluntaryExit) ProtoMessage() {}

func (x *VoluntaryExit) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoluntaryExit.ProtoReflect.Descriptor instead.
func (*VoluntaryExit) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{13}
}

func (x *VoluntaryExit) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *VoluntaryExit) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#proposerslashing
type ProposerSlashing struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Header_1      *SignedBeaconBlockHeader `protobuf:"bytes,1,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header_2      *SignedBeaconBlockHeader `protobuf:"bytes,2,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposerSlashing) Reset() {
	*x = ProposerSlashing{}
	mi := &file_eth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposerSlashing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposerSlashing) ProtoMessage() {}

func (x *ProposerSlashing) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposerSlashing.ProtoReflect.Descriptor instead.
func (*ProposerSlashing) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{14}
}

func (x *ProposerSlashing) GetHeader_1() *SignedBeaconBlockHeader {
	if x != nil {
		return x.Header_1
	}
	return nil
}

func (x *ProposerSlashing) GetHeader_2() *SignedBeaconBlockHeader {
	if x != nil {
		return x.Header_2
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#proposerslashing
type AttesterSlashing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestation_1 *IndexedAttestation    `protobuf:"bytes,1,opt,name=attestation_1,json=attestation1,proto3" json:"attestation_1,omitempty"`
	Attestation_2 *IndexedAttestation    `protobuf:"bytes,2,opt,name=attestation_2,json=attestation2,proto3" json:"attestation_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttesterSlashing) Reset() {
	*x = AttesterSlashing{}
	mi := &file_eth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttesterSlashing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttesterSlashing) ProtoMessage() {}

func (x *AttesterSlashing) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttesterSlashing.ProtoReflect.Descriptor instead.
func (*AttesterSlashing) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{15}
}

func (x *AttesterSlashing) GetAttestation_1() *IndexedAttestation {
	if x != nil {
		return x.Attestation_1
	}
	return nil
}

func (x *AttesterSlashing) GetAttestation_2() *IndexedAttestation {
	if x != nil {
		return x.Attestation_2
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#indexedattestation
type IndexedAttestation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AttestingIndices []uint64               `protobuf:"varint,1,rep,packed,name=attesting_indices,json=attestingIndices,proto3" json:"attesting_indices,omitempty"`
	Data             *AttestationData       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature        []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IndexedAttestation) Reset() {
	*x = IndexedAttestation{}
	mi := &file_eth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedAttestation) ProtoMessage() {}

func (x *IndexedAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedAttestation.ProtoReflect.Descriptor instead.
func (*IndexedAttestation) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{16}
}

func (x *IndexedAttestation) GetAttestingIndices() []uint64 {
	if x != nil {
		return x.AttestingIndices
	}
	return nil
}

func (x *IndexedAttestation) GetData() *AttestationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IndexedAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#attestationdata
type AttestationData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Index           uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	BeaconBlockRoot []byte                 `protobuf:"bytes,3,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty"`
	Source          *Checkpoint            `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target          *Checkpoint            `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestationData) Reset() {
	*x = AttestationData{}
	mi := &file_eth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationData) ProtoMessage() {}

func (x *AttestationData) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationData.ProtoReflect.Descriptor instead.
func (*AttestationData) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{17}
}

func (x *AttestationData) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AttestationData) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AttestationData) GetBeaconBlockRoot() []byte {
	if x != nil {
		return x.BeaconBlockRoot
	}
	return nil
}

func (x *AttestationData) GetSource() *Checkpoint {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AttestationData) GetTarget() *Checkpoint {
	if x != nil {
		return x.Target
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#checkpoint
type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Root          []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_eth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{18}
}

func (x *Checkpoint) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Checkpoint) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#attestation
type Attestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AggregationBits []byte                 `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty"`
	Data            *AttestationData       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature       []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_eth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{19}
}

func (x *Attestation) GetAggregationBits() []byte {
	if x != nil {
		return x.AggregationBits
	}
	return nil
}

func (x *Attestation) GetData() *AttestationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#deposit
type Deposit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         [][]byte               `protobuf:"bytes,1,rep,name=proof,proto3" json:"proof,omitempty"`
	Data          *DepositData           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	mi := &file_eth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{20}
}

func (x *Deposit) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Deposit) GetData() *DepositData {
	if x != nil {
		return x.Data
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#depositdata
type DepositData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Pubkey                []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	WithdrawalCredentials []byte                 `protobuf:"bytes,2,opt,name=withdrawal_credentials,json=withdrawalCredentials,proto3" json:"withdrawal_credentials,omitempty"`
	Amount                uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Signature             []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DepositData) Reset() {
	*x = DepositData{}
	mi := &file_eth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositData) ProtoMessage() {}

func (x *DepositData) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositData.ProtoReflect.Descriptor instead.
func (*DepositData) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{21}
}

func (x *DepositData) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *DepositData) GetWithdrawalCredentials() []byte {
	if x != nil {
		return x.WithdrawalCredentials
	}
	return nil
}

func (x *DepositData) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md#syncaggregate
type SyncAggregate struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SyncCommitteeBits      []byte                 `protobuf:"bytes,1,opt,name=sync_committee_bits,json=syncCommitteeBits,proto3" json:"sync_committee_bits,omitempty"`
	SyncCommitteeSignature []byte                 `protobuf:"bytes,2,opt,name=sync_committee_signature,json=syncCommitteeSignature,proto3" json:"sync_committee_signature,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncAggregate) Reset() {
	*x = SyncAggregate{}
	mi := &file_eth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAggregate) ProtoMessage() {}

func (x *SyncAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAggregate.ProtoReflect.Descriptor instead.
func (*SyncAggregate) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{22}
}

func (x *SyncAggregate) GetSyncCommitteeBits() []byte {
	if x != nil {
		return x.SyncCommitteeBits
	}
	return nil
}

func (x *SyncAggregate) GetSyncCommitteeSignature() []byte {
	if x != nil {
		return x.SyncCommitteeSignature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#signedblstoexecutionchange
type SignedBLSToExecutionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *BLSToExecutionChange  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBLSToExecutionChange) Reset() {
	*x = SignedBLSToExecutionChange{}
	mi := &file_eth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBLSToExecutionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBLSToExecutionChange) ProtoMessage() {}

func (x *SignedBLSToExecutionChange) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBLSToExecutionChange.ProtoReflect.Descriptor instead.
func (*SignedBLSToExecutionChange) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{23}
}

func (x *SignedBLSToExecutionChange) GetMessage() *BLSToExecutionChange {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedBLSToExecutionChange) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#blstoexecutionchange
type BLSToExecutionChange struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ValidatorIndex     uint64                 `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	FromBlsPubkey      []byte                 `protobuf:"bytes,2,opt,name=from_bls_pubkey,json=fromBlsPubkey,proto3" json:"from_bls_pubkey,omitempty"`
	ToExecutionAddress []byte                 `protobuf:"bytes,3,opt,name=to_execution_address,json=toExecutionAddress,proto3" json:"to_execution_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BLSToExecutionChange) Reset() {
	*x = BLSToExecutionChange{}
	mi := &file_eth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLSToExecutionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLSToExecutionChange) ProtoMessage() {}

func (x *BLSToExecutionChange) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLSToExecutionChange.ProtoReflect.Descriptor instead.
func (*BLSToExecutionChange) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{24}
}

func (x *BLSToExecutionChange) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *BLSToExecutionChange) GetFromBlsPubkey() []byte {
	if x != nil {
		return x.FromBlsPubkey
	}
	return nil
}

func (x *BLSToExecutionChange) GetToExecutionAddress() []byte {
	if x != nil {
		return x.ToExecutionAddress
	}
	return nil
}

var File_eth_proto protoreflect.FileDescriptor

const file_eth_proto_rawDesc = "" +
	"\n" +
	"\teth.proto\x12\x03eth\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x03\n" +
	"\vTransaction\x12\x13\n" +
	"\x02to\x18\x01 \x01(\fH\x00R\x02to\x88\x01\x01\x12\x10\n" +
	"\x03gas\x18\x02 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\x03 \x01(\x04R\bgasPrice\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\x12\x17\n" +
	"\x04from\x18\b \x01(\fH\x01R\x04from\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\t \x01(\rR\x04type\x12\x17\n" +
	"\amax_fee\x18\n" +
	" \x01(\x04R\x06maxFee\x12!\n" +
	"\fpriority_fee\x18\v \x01(\x04R\vpriorityFee\x12\f\n" +
	"\x01v\x18\f \x01(\x04R\x01v\x12\f\n" +
	"\x01r\x18\r \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x0e \x01(\fR\x01s\x12\x18\n" +
	"\achainId\x18\x0f \x01(\rR\achainId\x121\n" +
	"\vaccess_list\x18\x10 \x03(\v2\x10.eth.AccessTupleR\n" +
	"accessListB\x05\n" +
	"\x03_toB\a\n" +
	"\x05_from\"J\n" +
	"\vAccessTuple\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\fR\vstorageKeys\"}\n" +
	"\x10ExecutionPayload\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.eth.ExecutionPayloadHeaderR\x06header\x124\n" +
	"\ftransactions\x18\x02 \x03(\v2\x10.eth.TransactionR\ftransactions\"\xb4\x04\n" +
	"\x16ExecutionPayloadHeader\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12#\n" +
	"\rfee_recipient\x18\x02 \x01(\fR\ffeeRecipient\x12\x1d\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fR\tstateRoot\x12#\n" +
	"\rreceipts_root\x18\x04 \x01(\fR\freceiptsRoot\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fR\tlogsBloom\x12\x1f\n" +
	"\vprev_randao\x18\x06 \x01(\fR\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\v \x01(\fR\textraData\x12'\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fR\rbaseFeePerGas\x12\x1d\n" +
	"\n" +
	"block_hash\x18\r \x01(\fR\tblockHash\x12+\n" +
	"\x11transactions_root\x18\x0e \x01(\fR\x10transactionsRoot\x12.\n" +
	"\x10withdrawals_root\x18\x0f \x01(\fH\x00R\x0fwithdrawalsRoot\x88\x01\x01B\x13\n" +
	"\x11_withdrawals_root\"\xb2\x01\n" +
	"\vBeaconBlock\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12%\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04R\rproposerIndex\x12\x1f\n" +
	"\vparent_root\x18\x03 \x01(\fR\n" +
	"parentRoot\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12(\n" +
	"\x04body\x18\x05 \x01(\v2\x14.eth.BeaconBlockBodyR\x04body\"\xc0\x01\n" +
	"\x12CompactBeaconBlock\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12%\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04R\rproposerIndex\x12\x1f\n" +
	"\vparent_root\x18\x03 \x01(\fR\n" +
	"parentRoot\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12/\n" +
	"\x04body\x18\x05 \x01(\v2\x1b.eth.CompactBeaconBlockBodyR\x04body\"]\n" +
	"\x11SignedBeaconBlock\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.eth.BeaconBlockR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x86\x05\n" +
	"\x0fBeaconBlockBody\x12#\n" +
	"\rrandao_reveal\x18\x01 \x01(\fR\frandaoReveal\x12*\n" +
	"\teth1_data\x18\x02 \x01(\v2\r.eth.Eth1DataR\beth1Data\x12\x1a\n" +
	"\bgraffiti\x18\x03 \x01(\fR\bgraffiti\x12D\n" +
	"\x12proposer_slashings\x18\x04 \x03(\v2\x15.eth.ProposerSlashingR\x11proposerSlashings\x12D\n" +
	"\x12attester_slashings\x18\x05 \x03(\v2\x15.eth.AttesterSlashingR\x11attesterSlashings\x124\n" +
	"\fattestations\x18\x06 \x03(\v2\x10.eth.AttestationR\fattestations\x12(\n" +
	"\bdeposits\x18\a \x03(\v2\f.eth.DepositR\bdeposits\x12A\n" +
	"\x0fvoluntary_exits\x18\b \x03(\v2\x18.eth.SignedVoluntaryExitR\x0evoluntaryExits\x129\n" +
	"\x0esync_aggregate\x18\t \x01(\v2\x12.eth.SyncAggregateR\rsyncAggregate\x12B\n" +
	"\x11execution_payload\x18\n" +
	" \x01(\v2\x15.eth.ExecutionPayloadR\x10executionPayload\x12X\n" +
	"\x18bls_to_execution_changes\x18\v \x03(\v2\x1f.eth.SignedBLSToExecutionChangeR\x15blsToExecutionChanges\"\xc9\x04\n" +
	"\x16CompactBeaconBlockBody\x12#\n" +
	"\rrandao_reveal\x18\x01 \x01(\fR\frandaoReveal\x12*\n" +
	"\teth1_data\x18\x02 \x01(\v2\r.eth.Eth1DataR\beth1Data\x12\x1a\n" +
	"\bgraffiti\x18\x03 \x01(\fR\bgraffiti\x12D\n" +
	"\x12proposer_slashings\x18\x04 \x03(\v2\x15.eth.ProposerSlashingR\x11proposerSlashings\x12D\n" +
	"\x12attester_slashings\x18\x05 \x03(\v2\x15.eth.AttesterSlashingR\x11attesterSlashings\x124\n" +
	"\fattestations\x18\x06 \x03(\v2\x10.eth.AttestationR\fattestations\x12(\n" +
	"\bdeposits\x18\a \x03(\v2\f.eth.DepositR\bdeposits\x12A\n" +
	"\x0fvoluntary_exits\x18\b \x03(\v2\x18.eth.SignedVoluntaryExitR\x0evoluntaryExits\x129\n" +
	"\x0esync_aggregate\x18\t \x01(\v2\x12.eth.SyncAggregateR\rsyncAggregate\x12X\n" +
	"\x18bls_to_execution_changes\x18\n" +
	" \x03(\v2\x1f.eth.SignedBLSToExecutionChangeR\x15blsToExecutionChanges\"i\n" +
	"\x17SignedBeaconBlockHeader\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.eth.BeaconBlockHeaderR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xab\x01\n" +
	"\x11BeaconBlockHeader\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12%\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04R\rproposerIndex\x12\x1f\n" +
	"\vparent_root\x18\x03 \x01(\fR\n" +
	"parentRoot\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12\x1b\n" +
	"\tbody_root\x18\x05 \x01(\fR\bbodyRoot\"q\n" +
	"\bEth1Data\x12!\n" +
	"\fdeposit_root\x18\x01 \x01(\fR\vdepositRoot\x12#\n" +
	"\rdeposit_count\x18\x02 \x01(\x04R\fdepositCount\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\"a\n" +
	"\x13SignedVoluntaryExit\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.eth.VoluntaryExitR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"N\n" +
	"\rVoluntaryExit\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12'\n" +
	"\x0fvalidator_index\x18\x02 \x01(\x04R\x0evalidatorIndex\"\x84\x01\n" +
	"\x10ProposerSlashing\x127\n" +
	"\bheader_1\x18\x01 \x01(\v2\x1c.eth.SignedBeaconBlockHeaderR\aheader1\x127\n" +
	"\bheader_2\x18\x02 \x01(\v2\x1c.eth.SignedBeaconBlockHeaderR\aheader2\"\x8e\x01\n" +
	"\x10AttesterSlashing\x12<\n" +
	"\rattestation_1\x18\x01 \x01(\v2\x17.eth.IndexedAttestationR\fattestation1\x12<\n" +
	"\rattestation_2\x18\x02 \x01(\v2\x17.eth.IndexedAttestationR\fattestation2\"\x89\x01\n" +
	"\x12IndexedAttestation\x12+\n" +
	"\x11attesting_indices\x18\x01 \x03(\x04R\x10attestingIndices\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.eth.AttestationDataR\x04data\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xb9\x01\n" +
	"\x0fAttestationData\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12*\n" +
	"\x11beacon_block_root\x18\x03 \x01(\fR\x0fbeaconBlockRoot\x12'\n" +
	"\x06source\x18\x04 \x01(\v2\x0f.eth.CheckpointR\x06source\x12'\n" +
	"\x06target\x18\x05 \x01(\v2\x0f.eth.CheckpointR\x06target\"6\n" +
	"\n" +
	"Checkpoint\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\"\x80\x01\n" +
	"\vAttestation\x12)\n" +
	"\x10aggregation_bits\x18\x01 \x01(\fR\x0faggregationBits\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.eth.AttestationDataR\x04data\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"E\n" +
	"\aDeposit\x12\x14\n" +
	"\x05proof\x18\x01 \x03(\fR\x05proof\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.eth.DepositDataR\x04data\"\x92\x01\n" +
	"\vDepositData\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x125\n" +
	"\x16withdrawal_credentials\x18\x02 \x01(\fR\x15withdrawalCredentials\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"y\n" +
	"\rSyncAggregate\x12.\n" +
	"\x13sync_committee_bits\x18\x01 \x01(\fR\x11syncCommitteeBits\x128\n" +
	"\x18sync_committee_signature\x18\x02 \x01(\fR\x16syncCommitteeSignature\"o\n" +
	"\x1aSignedBLSToExecutionChange\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.eth.BLSToExecutionChangeR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x99\x01\n" +
	"\x14BLSToExecutionChange\x12'\n" +
	"\x0fvalidator_index\x18\x01 \x01(\x04R\x0evalidatorIndex\x12&\n" +
	"\x0ffrom_bls_pubkey\x18\x02 \x01(\fR\rfromBlsPubkey\x120\n" +
	"\x14to_execution_address\x18\x03 \x01(\fR\x12toExecutionAddressb\x06proto3"

var (
	file_eth_proto_rawDescOnce sync.Once
	file_eth_proto_rawDescData []byte
)

func file_eth_proto_rawDescGZIP() []byte {
	file_eth_proto_rawDescOnce.Do(func() {
		file_eth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eth_proto_rawDesc), len(file_eth_proto_rawDesc)))
	})
	return file_eth_proto_rawDescData
}

var file_eth_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_eth_proto_goTypes = []any{
	(*Transaction)(nil),                // 0: eth.Transaction
	(*AccessTuple)(nil),                // 1: eth.AccessTuple
	(*ExecutionPayload)(nil),           // 2: eth.ExecutionPayload
	(*ExecutionPayloadHeader)(nil),     // 3: eth.ExecutionPayloadHeader
	(*BeaconBlock)(nil),                // 4: eth.BeaconBlock
	(*CompactBeaconBlock)(nil),         // 5: eth.CompactBeaconBlock
	(*SignedBeaconBlock)(nil),          // 6: eth.SignedBeaconBlock
	(*BeaconBlockBody)(nil),            // 7: eth.BeaconBlockBody
	(*CompactBeaconBlockBody)(nil),     // 8: eth.CompactBeaconBlockBody
	(*SignedBeaconBlockHeader)(nil),    // 9: eth.SignedBeaconBlockHeader
	(*BeaconBlockHeader)(nil),          // 10: eth.BeaconBlockHeader
	(*Eth1Data)(nil),                   // 11: eth.Eth1Data
	(*SignedVoluntaryExit)(nil),        // 12: eth.SignedVoluntaryExit
	(*VoluntaryExit)(nil),              // 13: eth.VoluntaryExit
	(*ProposerSlashing)(nil),           // 14: eth.ProposerSlashing
	(*AttesterSlashing)(nil),           // 15: eth.AttesterSlashing
	(*IndexedAttestation)(nil),         // 16: eth.IndexedAttestation
	(*AttestationData)(nil),            // 17: eth.AttestationData
	(*Checkpoint)(nil),                 // 18: eth.Checkpoint
	(*Attestation)(nil),                // 19: eth.Attestation
	(*Deposit)(nil),                    // 20: eth.Deposit
	(*DepositData)(nil),                // 21: eth.DepositData
	(*SyncAggregate)(nil),              // 22: eth.SyncAggregate
	(*SignedBLSToExecutionChange)(nil), // 23: eth.SignedBLSToExecutionChange
	(*BLSToExecutionChange)(nil),       // 24: eth.BLSToExecutionChange
}
var file_eth_proto_depIdxs = []int32{
	1,  // 0: eth.Transaction.access_list:type_name -> eth.AccessTuple
	3,  // 1: eth.ExecutionPayload.header:type_name -> eth.ExecutionPayloadHeader
	0,  // 2: eth.ExecutionPayload.transactions:type_name -> eth.Transaction
	7,  // 3: eth.BeaconBlock.body:type_name -> eth.BeaconBlockBody
	8,  // 4: eth.CompactBeaconBlock.body:type_name -> eth.CompactBeaconBlockBody
	4,  // 5: eth.SignedBeaconBlock.message:type_name -> eth.BeaconBlock
	11, // 6: eth.BeaconBlockBody.eth1_data:type_name -> eth.Eth1Data
	14, // 7: eth.BeaconBlockBody.proposer_slashings:type_name -> eth.ProposerSlashing
	15, // 8: eth.BeaconBlockBody.attester_slashings:type_name -> eth.AttesterSlashing
	19, // 9: eth.BeaconBlockBody.attestations:type_name -> eth.Attestation
	20, // 10: eth.BeaconBlockBody.deposits:type_name -> eth.Deposit
	12, // 11: eth.BeaconBlockBody.voluntary_exits:type_name -> eth.SignedVoluntaryExit
	22, // 12: eth.BeaconBlockBody.sync_aggregate:type_name -> eth.SyncAggregate
	2,  // 13: eth.BeaconBlockBody.execution_payload:type_name -> eth.ExecutionPayload
	23, // 14: eth.BeaconBlockBody.bls_to_execution_changes:type_name -> eth.SignedBLSToExecutionChange
	11, // 15: eth.CompactBeaconBlockBody.eth1_data:type_name -> eth.Eth1Data
	14, // 16: eth.CompactBeaconBlockBody.proposer_slashings:type_name -> eth.ProposerSlashing
	15, // 17: eth.CompactBeaconBlockBody.attester_slashings:type_name -> eth.AttesterSlashing
	19, // 18: eth.CompactBeaconBlockBody.attestations:type_name -> eth.Attestation
	20, // 19: eth.CompactBeaconBlockBody.deposits:type_name -> eth.Deposit
	12, // 20: eth.CompactBeaconBlockBody.voluntary_exits:type_name -> eth.SignedVoluntaryExit
	22, // 21: eth.CompactBeaconBlockBody.sync_aggregate:type_name -> eth.SyncAggregate
	23, // 22: eth.CompactBeaconBlockBody.bls_to_execution_changes:type_name -> eth.SignedBLSToExecutionChange
	10, // 23: eth.SignedBeaconBlockHeader.message:type_name -> eth.BeaconBlockHeader
	13, // 24: eth.SignedVoluntaryExit.message:type_name -> eth.VoluntaryExit
	9,  // 25: eth.ProposerSlashing.header_1:type_name -> eth.SignedBeaconBlockHeader
	9,  // 26: eth.ProposerSlashing.header_2:type_name -> eth.SignedBeaconBlockHeader
	16, // 27: eth.AttesterSlashing.attestation_1:type_name -> eth.IndexedAttestation
	16, // 28: eth.AttesterSlashing.attestation_2:type_name -> eth.IndexedAttestation
	17, // 29: eth.IndexedAttestation.data:type_name -> eth.AttestationData
	18, // 30: eth.AttestationData.source:type_name -> eth.Checkpoint
	18, // 31: eth.AttestationData.target:type_name -> eth.Checkpoint
	17, // 32: eth.Attestation.data:type_name -> eth.AttestationData
	21, // 33: eth.Deposit.data:type_name -> eth.DepositData
	24, // 34: eth.SignedBLSToExecutionChange.message:type_name -> eth.BLSToExecutionChange
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_eth_proto_init() }
func file_eth_proto_init() {
	if File_eth_proto != nil {
		return
	}
	file_eth_proto_msgTypes[0].OneofWrappers = []any{}
	file_eth_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eth_proto_rawDesc), len(file_eth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eth_proto_goTypes,
		DependencyIndexes: file_eth_proto_depIdxs,
		MessageInfos:      file_eth_proto_msgTypes,
	}.Build()
	File_eth_proto = out.File
	file_eth_proto_goTypes = nil
	file_eth_proto_depIdxs = nil
}
